### ISSUE TITLE
Update Whisper version for Chowda (1)

### ISSUE THREAD

**Issue by DraxIndustries79** [WGBH-MLA/chowda#194]
## Acceptance:
- [x] Update to latest [Whisper v6](https://apps.clams.ai/whisper-wrapper/v6/)

**Comment by mrharpo** [comment]
We are actually using the latest version already with the `latest` tag.

See https://github.com/clamsproject/clams-deploy/blob/14af77d741d1ff99149d5d9665f0b3f0be664081/app-whisper-cpu/deploy.yml#L23

>         - image: ghcr.io/clamsproject/app-whisper-wrapper:latest
