### ISSUE TITLE
Dowloading all MMIF files for a batch no longer works

### ISSUE THREAD

**Issue by owencking** [WGBH-MLA/chowda#215]
### Description

When I click "Download MMIF", it should give me a zip file with the MMIF files (like it used to), but right now it doesn't give me anything.

### Reproduction steps

1. Go to this [batch](https://chowda.wgbh-mla.org/admin/batch/detail/59)
2. Click on "Download MMIF"
3. Click yes in confirmation pop-up
4. Receive no zip file

### Browsers

Chrome

**Comment by mrharpo** [comment]
@owencking Try it again. I think you caught it in a broken state while I was working on a related feature: #213 

I generalized the download logic to apply to batches, as well as individual MMIFS, so you should be able to download an MMIF directly from its detail page, or from the MMIF list view. Try it out!

**Comment by owencking** [comment]
Yeah, works for me now!  I can download a zip for the batch, and I can download the individual MMIF files.  Nice.

Closing the issue.

**Comment by owencking** [comment]
Yeah, works for me now! I can download a zip for the batch, and I can download the individual MMIF files. Nice.

Closing the issue.
